name: Keep Render API Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # lets you run manually too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://bill-api-v3-latest.onrender.com/health
